// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaIuNz_12xdMiQ8i6F_LXXM8Enbik9LjE',
    appId: '1:201053849491:web:89e0f110461eb790b9ca66',
    messagingSenderId: '201053849491',
    projectId: 'pet-planet-887d2',
    authDomain: 'pet-planet-887d2.firebaseapp.com',
    storageBucket: 'pet-planet-887d2.appspot.com',
    measurementId: 'G-MF5RXJHSRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpj6STQXkZAZ_bIFVmqPwB6YxhXoWNo0s',
    appId: '1:201053849491:android:3a1229879f7c79b0b9ca66',
    messagingSenderId: '201053849491',
    projectId: 'pet-planet-887d2',
    storageBucket: 'pet-planet-887d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYvv9586bqN_qOFGuXqt1HiP6GD1p8Fo',
    appId: '1:201053849491:ios:e64a2307261fb319b9ca66',
    messagingSenderId: '201053849491',
    projectId: 'pet-planet-887d2',
    storageBucket: 'pet-planet-887d2.appspot.com',
    iosClientId: '201053849491-dia60f2i1dpggitihsnvs9oract558em.apps.googleusercontent.com',
    iosBundleId: 'com.example.petplanet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiYvv9586bqN_qOFGuXqt1HiP6GD1p8Fo',
    appId: '1:201053849491:ios:e64a2307261fb319b9ca66',
    messagingSenderId: '201053849491',
    projectId: 'pet-planet-887d2',
    storageBucket: 'pet-planet-887d2.appspot.com',
    iosClientId: '201053849491-dia60f2i1dpggitihsnvs9oract558em.apps.googleusercontent.com',
    iosBundleId: 'com.example.petplanet',
  );
}
